#=================================================
#   Description: Build X-WRT using GitHub Actions
#   Lisence: MIT
#   Author: ptpt52
#=================================================

name: Build Jobs 25.04_b202512270010

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Create Github Release
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-24.04
    steps:
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
        name: X-WRT ${{ github.ref_name }}
        draft: false
        allowUpdates: true
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v4
      with:
        name: release_url
        path: release_url.txt
  build-ramips-mt7620:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E rm -rf /mnt/tmp-pv.img || true
        sudo -E df -h
        sudo -E ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install mergerfs build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E rm -rf /mnt/work /mnt/work_dir /data_dir
        sudo -E mkdir -p /data_dir
        sudo -E mkdir -p /mnt/work_dir
        sudo -E mkdir -p /mnt/work
        sudo -E chmod 777 /mnt/work /mnt/work_dir /data_dir
        sudo -E mergerfs -o defaults,allow_other,use_ino,category.create=mfs /mnt/work_dir:/data_dir /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/xzsajo/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp *.tar.gz /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ramips-mt7620" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ramips-mt7620
        path: /mnt/work/x-wrt/make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-ramips-mt7620-xiaomi_miwifi-r3
      id: asset-f17a9ef68bf3b2a2ebae502e937eb577
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-ramips-mt7620-xiaomi_miwifi-r3.zip
        asset_name: x-wrt-ramips-mt7620-xiaomi_miwifi-r3.zip
        asset_content_type: application/zip
        overwrite: true
